version: "3"
services:
  newsoftware-loja:
    container_name: newsoftware-loja
    image: newsoftware-loja:develop
    ports:
      - "3004:3001"
    build:
      context: docker/develop
    volumes:
      - .:/app
    networks:
      - newsoftware
    environment:
      - PORT=3001
      - MONGODB_URL=${MONGO_URL}
      - SECRET_OR_PRIVATE_KEY=${SECRET_OR_PRIVATE_KEY}

  newsoftware-loja-db:
    container_name: newsoftware-loja-db
    image: mongo
    volumes:
      - newsoftware-loja-db:/data/db
    networks:
      - newsoftware

volumes:
  newsoftware-loja-db:

networks:
  newsoftware:
    driver: bridge
